### ISSUE TITLE
how to implement an extension/plugin

### ISSUE THREAD

**Issue by jtydhr88** [Stability-AI/StableStudio#10]
As an extension developer for ‎AUTOMATIC1111 stable-diffusion-webui, I am wondering does StableStudio have the plan to support custom extension/plugin contributed by community?

**Comment by KAJdev** [comment]
You can read the plugin documentation here: https://github.com/Stability-AI/StableStudio/blob/main/packages/stablestudio-plugin/README.md

You can comment on the contract here: https://github.com/Stability-AI/StableStudio/issues/3

**Comment by Apolotoybo** [comment]
Than you and I appreciate you
