### ISSUE TITLE
Samplers do not show up in the selection box

### ISSUE THREAD

**Issue by Harvester62** [Stability-AI/StableStudio#42]
**Describe the bug**
If I click on the Sampler | Select a Sampler option the selection box opens but only the message "Loading Samplers ..." is being displayed, and no samplers are listed for selection. Changing model doesn't make any difference.

**To Reproduce**
as above described, search for the list of samplers but none is displayed

**Expected behavior**
The list of available samplers/schedulers should be retrieved and displayed in the selection box for selection.

**Screenshots**
![immagine](https://github.com/Stability-AI/StableStudio/assets/29801031/23db7ba7-5914-41e8-b4c2-febba46b8a33)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Firefox 
 - Version 113.0.1 (64 bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by KAJdev** [comment]
I cannot reproduce
![image](https://github.com/Stability-AI/StableStudio/assets/40004347/db65d17c-814d-43b6-b270-77735a48e3b1)

Could you provide more information regarding your environment?

**Comment by Harvester62** [comment]
Thank you for all your feedback and replies. For completeness of information, here follow the running environment details:
- Windows 10 Pro (64bit) [Microsoft Windows [Version 10.0.19045.2965]], 
- NodeJS has been just updated from v18.15.0 to v18.16.0 LTS (just in case), 
- Yarn should be shipped with NodeJS so not "installed", 
- Browser is Firefox Version 113.0.1 (64 bit), Python v3.10.6.

This is the console at startup (yarn and yarn dev):
![immagine](https://github.com/Stability-AI/StableStudio/assets/29801031/3024a34a-7eb7-49a5-9294-67d346a391b1)

Anyway, perhaps due to the updating of NodeJS, or for some other reasons, the Samplers are now being correctly displayed:
![immagine](https://github.com/Stability-AI/StableStudio/assets/29801031/c764b60a-7ced-4a9a-b567-09c5d73b8ee5)

If you don't disagree, I would close this bug report. Sorry for the false alarm.
