### ISSUE TITLE
DreamStudio's API Key is not retained and has to be inserted at every StableStudio session

### ISSUE THREAD

**Issue by Harvester62** [Stability-AI/StableStudio#43]
**Describe the bug**
The Dream Studio API Key is not retained after closing the program, therefore at the next restart it has to be inserted again.

**To Reproduce**
See above

**Expected behavior**
It would be convenient if the API Key, once inserted as required, could be someway stored locally, better if inside a separate, dedicated file so that the user might eventually, for any reasons, be able to delete it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Firefox
 - Version 113.0.1 (64 bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
Not really a bug per-se but more a usability suggestion.

**Comment by KAJdev** [comment]
The Stability API plugin stores your API key in localStorage in your browser, so it should persist as long as you visit from the same origin.

 I have just tested this and cannot seem to reproduce your issue.

**Comment by Harvester62** [comment]
I didn't save it in the browser, that's why. Thank you.
