### ISSUE TITLE
Not Working When Deployed over cloud server

### ISSUE THREAD

**Issue by SamarthGhante** [Stability-AI/StableStudio#45]
I deployed this on cloud servers running Ubuntu and everything was working as intended. 
However, when trying to access http://ServerIP:3000 in the browser, it did not work

**Comment by Aditya-13** [comment]
On which platform you've deployed it and what is the error you're getting?

**Comment by SamarthGhante** [comment]
> On which platform you've deployed it and what is the error you're getting?

I Deployed it on Ubuntu Server Hosted on Microsoft Azure; No Error logs but there is no application show when we hit the http://serverip:3000

**Comment by harrywang** [comment]
I think we should have a wiki page or something to document how to deploy on various cloud servers, e.g., aws, azure, vercel, etc.

**Comment by cruhl** [comment]
What happens if you build the application and use the compiled `dist` folder versus trying to run it via `yarn dev`?

**Comment by SamarthGhante** [comment]
> What happens if you build the application and use the compiled `dist` folder versus trying to run it via `yarn dev`?

Sry for late reply.
Same Issue; But Here is a quick fix.
Link a domain using reverse proxy services such as (nginx proxy manager) or use tunneling to access the `http://serverip:port`  & it will fix the issue. 
I don't why, but I think it coded such that it only opens on 127.0.0.1:3000 & it isn't possible when deployed over Cloud Server.
