### ISSUE TITLE
Generated images missing parameter info using WebUI backend

### ISSUE THREAD

**Issue by harrywang** [Stability-AI/StableStudio#72]
**Describe the bug**
After generating the images using WebUI backend from #25 and show the generation history, click the image and some parameter information is missing.

<img width="2077" alt="Screenshot 2023-05-25 at 3 19 49 PM" src="https://github.com/Stability-AI/StableStudio/assets/595772/be346c74-ee4a-4d9c-909b-0f123dc1e2bd">

<img width="2006" alt="Screenshot 2023-05-25 at 3 19 41 PM" src="https://github.com/Stability-AI/StableStudio/assets/595772/2073264b-906d-4271-9f54-fea084b00f45">

**Desktop (please complete the following information):**
MacBook Pro with Chrome

**Comment by jtydhr88** [comment]
@harrywang can you help to make a bit of tests? Just open your webui with no api mode, switch to PNG info tab, upload one image in txt2img or img2img folder to see how it works here? If it could not read information as well that would be the issue on webui side

**Comment by harrywang** [comment]
> @harrywang can you help to make a bit of tests? Just open your webui with no api mode, switch to PNG info tab, upload one image in txt2img or img2img folder to see how it works here? If it could not read information as well that would be the issue on webui side

@jtydhr88 
<img width="1906" alt="Screenshot 2023-05-25 at 7 57 11 PM" src="https://github.com/Stability-AI/StableStudio/assets/595772/ec15389b-a66f-4f2a-8e47-2c5cc87bac10">

Yes. No metadata saved in the PNG. 

It would be nice if we can have the metadata saved in PNG while using StableStuio via your WebUI plugin.

**Comment by harrywang** [comment]
I just tried another one, which has the metadata saved - all generated using using StableStuio via WebUI backend plugin. - not sure why some worked and some did not work.

<img width="2543" alt="Screenshot 2023-05-25 at 8 03 04 PM" src="https://github.com/Stability-AI/StableStudio/assets/595772/88a0e022-3b05-4524-b2eb-557352411867">

**Comment by harrywang** [comment]
just generated another one to confirm: the metadata is saved in PNG:
<img width="2556" alt="Screenshot 2023-05-25 at 8 16 23 PM" src="https://github.com/Stability-AI/StableStudio/assets/595772/009c389a-61cb-41fa-9abe-b4e4dfe8f45e">

but metadata is not properly shown in StableStudio:
<img width="2479" alt="Screenshot 2023-05-25 at 8 17 39 PM" src="https://github.com/Stability-AI/StableStudio/assets/595772/9f31377d-8806-465b-85b5-9426ed70d379">

**Comment by jtydhr88** [comment]
I guess I get the cause which is line break.
can you go to your local file https://github.com/Stability-AI/StableStudio/blob/552ddb4a3dbe4f23b69ad0169948899331eb0f2c/packages/stablestudio-plugin-webui/src/Utilities.ts#L57
and change **\n** to **\r**, to see it can fix the issue?

**Comment by harrywang** [comment]
> I guess I get the cause which is line break. can you go to your local file
> 
> https://github.com/Stability-AI/StableStudio/blob/552ddb4a3dbe4f23b69ad0169948899331eb0f2c/packages/stablestudio-plugin-webui/src/Utilities.ts#L57
> 
> 
> and change **\n** to **\r**, to see it can fix the issue?

No, the history images won't show after changing to **\r** with console error:

<img width="2560" alt="Screenshot 2023-05-25 at 9 53 40 PM" src="https://github.com/Stability-AI/StableStudio/assets/595772/b237e540-bb6b-44ba-8128-dd6b619d4719">

**Comment by KAJdev** [comment]
Is this likely an issue with themes? Can you verify that the text isn't white as well?

**Comment by harrywang** [comment]
> Is this likely an issue with themes? Can you verify that the value text isn't just white?

you are right - stupid me:
<img width="2493" alt="Screenshot 2023-05-25 at 11 05 31 PM" src="https://github.com/Stability-AI/StableStudio/assets/595772/f8a87ddb-2c55-47c4-bcdf-22a8cb605469">

I will fix this in our PR #67
