### ISSUE TITLE
How to run this in googl colab?

### ISSUE THREAD

**Issue by tralala87** [Stability-AI/StableStudio#75]
Hi. Trying to run this in colab, but the link page doesn't work. Any idea how to make this work?

!curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
!echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
!sudo apt-get update && sudo apt-get install yarn
!curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
!sudo apt-get install -y nodejs
!git clone https://github.com/Stability-AI/StableStudio.git
%cd StableStudio
!yarn
!yarn dev

**Comment by arch-user-france1** [comment]
Instead of installing yarn with a debian package, you can install it with `npm` like this: `npm i -g yarn`.

**Comment by tralala87** [comment]
Colab freezes of I do that :)

**Comment by arch-user-france1** [comment]
You should wait a little bit. Have you waited five minutes?

**Comment by tralala87** [comment]
I did. It never unfreezes.

**Comment by arch-user-france1** [comment]
> the link page doesn't work

What doesn't work???

**Comment by tralala87** [comment]
After running:

!curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
!echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
!sudo apt-get update && sudo apt-get install yarn
!curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
!sudo apt-get install -y nodejs
!git clone https://github.com/Stability-AI/StableStudio.git
%cd StableStudio
!yarn
!yarn dev

[localhost:3000](http://localhost:3000/) doesn't work (does not connect to anything)

**Comment by arch-user-france1** [comment]
`localhost` is the local computer. You must find a solution to forward your port from the Google Colab server to your computer.

**Comment by purgenetik** [comment]
> `localhost` is the local computer. You must find a solution to forward your port from the Google Colab server to your computer.

Solution with tunneling with cloudfare  service is [here](https://github.com/camenduru/StableStudio-colab)

**Comment by arch-user-france1** [comment]
I'd rather use ngrok.io, but the choice is not left to me.
Ah, there's a manual for that?

@tralala87, tell us if you need further guidance.
