### ISSUE TITLE
Stable Studio - yarn dev script missing?

### ISSUE THREAD

**Issue by kdwoell** [Stability-AI/StableStudio#91]
**Describe the bug**
Following steps in Quick Start guide produces Yarn dev script missing/not found error. Confirmed Stable Studio not running at localhost:3000

**To Reproduce**
1. Open command terminal
2. cd to Stable Studio directory in Home directory
3. Set active version of NVM 
>:~/StableStudio$ nvm use v20.3.1 
Now using node v20.3.1 (npm v9.6.7)

5. enter Yarn
>:~/StableStudio$ yarn
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 0s 45ms
>:~/StableStudio$ yarn dev
Usage Error: Couldn't find a script named "dev".

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
>:~/StableStudio$ 
6. enter 

**Expected behavior**
Expected no error msg

**Screenshots**
extract of command terminal session above.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Browser: Chrome or Chromium
 - Version: latest browser from repos

**Additional context**
Followed instructions in the Quick Start. Installed Node using NVM. Installed Yarn using corepackage.

**Comment by Tzahile** [comment]
I've just installed (arch linux) a fresh project locally, and `yarn dev` worked as expected.
Check the `package.json` and see if there's dev.

![image](https://github.com/Stability-AI/StableStudio/assets/13683050/aeb22bec-4cd3-4790-a566-bd83ff47bcd2)

**Comment by kdwoell** [comment]
Hmm.
I looked at the package.json file in a text editor. See below. No entry for a dev. I assume that's what you meant? 


``{
  "name": "StableStudio",
  "packageManager": "yarn@3.6.0"
}``

**Comment by kdwoell** [comment]
Apparently Yarn was not configured properly based on inspection of the package.json file. Re-installed Yarn. Then deleted the /StableStudio directory. Then followed the quick start guide. StableStudio was accessible from localhost:3000 in a browser.

**Comment by Tzahile** [comment]
If your problem is resolved, consider closing the issue.
I'm glad you managed :)

**Comment by kdwoell** [comment]
Resolved. apologies for not closing this issue.
