### ISSUE TITLE
StableStudio | browsers cannot establish a connection to the server at the localhost

### ISSUE THREAD

**Issue by Beto-Prado** [Stability-AI/StableStudio#97]
I have stalled and used the StableStudio on my Mac (and all the rest: node.js and yarn). The installation went all well and StableStudio was working perfectly fine. However, my browsers cannot establish a connection to the server at the localhost anymore. I am using http://localhost:3000/ or http://localhost:3000/settings

<img width="924" alt="Screen Shot 2023-07-26 at 1 24 35 pm" src="https://github.com/Stability-AI/StableStudio/assets/133840250/4a5b678e-dd2e-463f-ba83-41a3661119f6">

<img width="643" alt="Screen Shot 2023-07-26 at 1 25 13 pm" src="https://github.com/Stability-AI/StableStudio/assets/133840250/6b5a5fd8-7130-442e-969e-6a85091e88e1">

I have tried on both Safari 16.5.2 and Firefox 109.0.1 on my MacBook Pro 2019, OS Monterey 12.6.7

Am I missing something? Could someone help me with this please?!

**Comment by KAJdev** [comment]
what branch is this? and what commands did you run? Did you see Vite print out a local URL?

**Comment by Beto-Prado** [comment]
Hello KAJdev, 
Thank you for your quick reply!

Sorry my ignorance. I have followed the steps on the quick start from https://github.com/Stability-AI/StableStudio

<img width="882" alt="Screen Shot 2023-07-27 at 11 42 34 am" src="https://github.com/Stability-AI/StableStudio/assets/133840250/03b67024-3669-4a4b-ab99-5ffb6913b3b4">

Downloaded node.js 18.17.0 LTS for macOS from here https://nodejs.org/en/download

After installing, I have used StableStudio on my computer and it was all working well. But when I tried to access next time, it gave me those messages above.

Since everything was installed and have worked properly after installation, I thought all I had to do was to go to my browser and run StableStudio through the localhost link:

<img width="521" alt="Screen Shot 2023-07-27 at 11 59 20 am" src="https://github.com/Stability-AI/StableStudio/assets/133840250/8457cdf5-8aa7-4957-85c2-c22a44b61a89">

<img width="809" alt="Screen Shot 2023-07-27 at 12 04 17 pm" src="https://github.com/Stability-AI/StableStudio/assets/133840250/9c8ccbb1-0727-4a37-80a9-ee24491f7bf5">

Do I need to do anything else to run StableStudio again? Should I run any command via terminal before trying the localhost link?

Thanks!

**Comment by Beto-Prado** [comment]
Hey KAJdev! Nevermind! I managed to make it work. 

I figure that out. We do need to run the commands every time before actually go to the localhost link. 

Sorry to waste your time, I am new in the platform and have not posted it properly.
